import { describe, expect, it } from 'vitest';
import { parseQuoteDoc } from './parseQuoteDoc';

// No real founder-uploaded quote doc to calibrate against yet — this is a
// representative sample of what a quotation typically looks like once
// extracted to plain text (headers, a scope list with prices, boilerplate
// terms, a signature block). Tune against a real one once it's tried.
const SAMPLE = `
AgastyaOne — Quotation
Prepared for: Banglore Dental Clinic
Date: 20/08/2026

Scope of Work
Dental Website Development - ₹80,000
Google Business Profile Optimization ₹25,000
Local SEO setup, delivered within 2 weeks

Page 1 of 2

Terms and Conditions
This quotation is valid for thirty days from the date of issue and is subject to change without prior written notice.
GST 18% extra
Total: ₹1,05,000

Contact: agastya@agastyaone.com
+91 98765 43210
www.agastyaone.com

Signature
`;

describe('parseQuoteDoc', () => {
  it('extracts scope-of-work lines with their prices, stripped out of the text', () => {
    const { items } = parseQuoteDoc(SAMPLE);
    const website = items.find((i) => i.text.includes('Dental Website Development'));
    expect(website?.price).toBe('₹80,000');
    expect(website?.text).not.toContain('₹');

    const gbp = items.find((i) => i.text.includes('Google Business Profile'));
    expect(gbp?.price).toBe('₹25,000');
  });

  it('detects a relative deadline window', () => {
    const { items } = parseQuoteDoc(SAMPLE);
    const seo = items.find((i) => i.text.includes('Local SEO'));
    expect(seo?.deadline).toBe('within 2 weeks');
  });

  it('drops page furniture, totals, GST lines, contact details and the signature block', () => {
    const { items } = parseQuoteDoc(SAMPLE);
    const texts = items.map((i) => i.text.toLowerCase());
    expect(texts.some((t) => t.startsWith('page'))).toBe(false);
    expect(texts.some((t) => t.includes('gst'))).toBe(false);
    expect(texts.some((t) => t.startsWith('total'))).toBe(false);
    expect(texts.some((t) => t.includes('@'))).toBe(false);
    expect(texts.some((t) => /^\+?\d[\d\s-]{7,}$/.test(t))).toBe(false);
    expect(texts.some((t) => t === 'signature')).toBe(false);
  });

  it('drops the long prose terms sentence but keeps short scope bullets', () => {
    const { items } = parseQuoteDoc(SAMPLE);
    expect(items.some((i) => i.text.includes('valid for thirty days'))).toBe(false);
    expect(items.length).toBeGreaterThanOrEqual(3);
  });

  it('handles bulleted/numbered lines by stripping the marker', () => {
    const { items } = parseQuoteDoc('- Discovery call\n1. Design mockup\n• Content collected');
    expect(items.map((i) => i.text)).toEqual(['Discovery call', 'Design mockup', 'Content collected']);
  });

  it('returns no items for an empty or whitespace-only document', () => {
    expect(parseQuoteDoc('').items).toEqual([]);
    expect(parseQuoteDoc('   \n\n  ').items).toEqual([]);
  });

  it('caps extraction at 60 items so a malformed extraction cannot flood the review screen', () => {
    const many = Array.from({ length: 200 }, (_, i) => `Line item number ${i}`).join('\n');
    expect(parseQuoteDoc(many).items.length).toBe(60);
  });
});

// Real text pulled with mammoth.extractRawText from a document generated by
// the agastyaone-quote skill's own generate_quote.js against its own real
// example input (examples/bangalore-dental.json) — not a guess. Verifies
// the anchor-based path actually matches the founder's real quote shape.
const REAL_AGASTYAONE_QUOTE = `
AGASTYAONE

Digital Growth Systems for Dental Clinics

Digital Growth Quotation

Website · Local SEO · Google Business Profile · Automation

Prepared For

Bangalore Dental & Cosmetology Institute, Banashankari

Contact Person

[Contact Name, Designation]

Quote Reference

AGO-Q-2026-001

Date

11 August 2026

Valid Until

26 August 2026

Prepared by

Agastya Kancharla

Founder, AgastyaOne

89515 53531 · agastya@agastyaone.com · agastyaone.com

11 August 2026

Dear [Contact Name],

Thank you for taking the time to meet with us. Following our discussion, this quotation sets out the scope, deliverables, and investment for the digital growth system we discussed for Bangalore Dental & Cosmetology Institute, Banashankari.

Each section below reflects exactly what was agreed — what you receive as part of the one-time setup, and what AgastyaOne continues to manage for you every month as part of the Monthly Growth Plan. Pricing is drawn directly from our published Commercial Catalogue, so there are no hidden charges.

We're happy to walk through any part of this quotation on a call before you confirm.

Local Visibility & Discovery

Google Business Profile

Setup Includes

Audit

Optimization

Verification support

Categories & services

Initial posts

Every Month

Weekly posts

Review responses

Photo updates

Insights report

Monitoring

What We're Fixing — Based on Your Audit

Here's exactly what our audit found, and what we'll correct as part of the setup above:

NAP & Business Identity

Correct business name spelling ("Cosmetolgy" → "Cosmetology") and align with Google's naming guidelines

Standardize your primary contact number across Google and existing directory listings (JustDial, etc.)

Beyond This Quote — Additional Opportunities

Your Google Business Profile is the foundation, but real local dominance comes from a consistent presence across the web.

Website

A dedicated website gives you a home base beyond Google Maps.

These are not part of the scope or pricing below — happy to share pricing and build a combined plan whenever you're ready.

Investment Summary

ONE-TIME INVESTMENT

₹3,000

Setup & optimization

MONTHLY GROWTH PLAN

OPTIONAL — IF REQUIRED

₹2,000/mo

Ongoing management

Service

One-Time Investment

Monthly Growth Plan (Optional)

Google Business Profile

₹3,000

₹2,000/mo

TOTAL (selected services only)

₹3,000

₹2,000/mo

* Optional monthly plans are billed only if you choose to continue them after setup.

What Happens Next

1.  Acceptance & Advance Payment — you confirm this quotation and share the agreed advance.

Payment Terms

One-Time Investment: 50% advance to begin work, 50% on delivery/launch.

Terms & Validity

This quotation is valid for 15 days from the date above.

Acceptance

By signing below, both parties confirm agreement to the scope and pricing outlined in this quotation.

For the Clinic

For AgastyaOne

Name: _______________________

Name: _______________________

AGASTYAONE

agastyaone.com  ·  agastya@agastyaone.com  ·  89515 53531
`;

describe('parseQuoteDoc — real AgastyaOne quote template', () => {
  it('extracts exactly the real Setup Includes / Every Month bullets, in order', () => {
    const { items } = parseQuoteDoc(REAL_AGASTYAONE_QUOTE);
    expect(items.map((i) => i.text)).toEqual([
      'Audit',
      'Optimization',
      'Verification support',
      'Categories & services',
      'Initial posts',
      'Weekly posts',
      'Review responses',
      'Photo updates',
      'Insights report',
      'Monitoring'
    ]);
  });

  it('categorizes every item under the service name and prices it from Investment Summary', () => {
    const { items } = parseQuoteDoc(REAL_AGASTYAONE_QUOTE);
    for (const item of items) {
      expect(item.category).toBe('Google Business Profile');
      expect(item.price).toBe('₹3,000');
      expect(item.deadline).toBeUndefined();
    }
  });

  it('excludes every non-scope section — letterhead, title, info table, audit findings, upsell, investment table, next steps, terms, acceptance', () => {
    const { items } = parseQuoteDoc(REAL_AGASTYAONE_QUOTE);
    const texts = items.map((i) => i.text);
    const noise = [
      'AGASTYAONE',
      'Digital Growth Systems for Dental Clinics',
      'Digital Growth Quotation',
      'Prepared For',
      'Bangalore Dental & Cosmetology Institute, Banashankari',
      'Google Business Profile', // the category itself, never an item's own text
      "NAP & Business Identity",
      'Website',
      'TOTAL (selected services only)',
      'What Happens Next',
      'Payment Terms',
      'Acceptance',
      'Name: _______________________'
    ];
    for (const line of noise) expect(texts).not.toContain(line);
    expect(items.length).toBe(10);
  });
});

// Synthetic but structurally identical to the real multi-service case
// (two "Service / One-Time Investment / Monthly Growth Plan" table rows
// plus a TOTAL row) — the real example only has one service, so this
// covers price-per-category disambiguation between two services.
const MULTI_SERVICE_QUOTE = `
AGASTYAONE

Digital Growth Quotation

Prepared For

Test Clinic

Local Visibility & Discovery

Google Business Profile

Setup Includes

Audit

Optimization

Every Month

Weekly posts

Review responses

Website Development

Setup Includes

Design mockup

Pages built

Every Month

Hosting

Maintenance

Investment Summary

Service

One-Time Investment

Monthly Growth Plan

Google Business Profile

₹3,000

₹2,000/mo

Website Development

₹80,000

TOTAL (selected services only)

₹83,000

₹2,000/mo

What Happens Next

1.  Acceptance & Advance Payment — you confirm this quotation.

Acceptance

By signing below, both parties confirm agreement.
`;

describe('parseQuoteDoc — multiple services', () => {
  it('gives each service its own correct price, not the other service\'s or the total', () => {
    const { items } = parseQuoteDoc(MULTI_SERVICE_QUOTE);
    const gbp = items.filter((i) => i.category === 'Google Business Profile');
    const web = items.filter((i) => i.category === 'Website Development');
    expect(gbp.map((i) => i.text)).toEqual(['Audit', 'Optimization', 'Weekly posts', 'Review responses']);
    expect(gbp.every((i) => i.price === '₹3,000')).toBe(true);
    expect(web.map((i) => i.text)).toEqual(['Design mockup', 'Pages built', 'Hosting', 'Maintenance']);
    expect(web.every((i) => i.price === '₹80,000')).toBe(true);
  });
});
