import { describe, expect, it } from 'vitest';
import { parseQuoteDoc } from './parseQuoteDoc';

// No real founder-uploaded quote doc to calibrate against yet — this is a
// representative sample of what a quotation typically looks like once
// extracted to plain text (headers, a scope list with prices, boilerplate
// terms, a signature block). Tune against a real one once it's tried.
const SAMPLE = `
AgastyaOne — Quotation
Prepared for: Banglore Dental Clinic
Date: 20/08/2026

Scope of Work
Dental Website Development - ₹80,000
Google Business Profile Optimization ₹25,000
Local SEO setup, delivered within 2 weeks

Page 1 of 2

Terms and Conditions
This quotation is valid for thirty days from the date of issue and is subject to change without prior written notice.
GST 18% extra
Total: ₹1,05,000

Contact: agastya@agastyaone.com
+91 98765 43210
www.agastyaone.com

Signature
`;

describe('parseQuoteDoc', () => {
  it('extracts scope-of-work lines with their prices, stripped out of the text', () => {
    const { items } = parseQuoteDoc(SAMPLE);
    const website = items.find((i) => i.text.includes('Dental Website Development'));
    expect(website?.price).toBe('₹80,000');
    expect(website?.text).not.toContain('₹');

    const gbp = items.find((i) => i.text.includes('Google Business Profile'));
    expect(gbp?.price).toBe('₹25,000');
  });

  it('detects a relative deadline window', () => {
    const { items } = parseQuoteDoc(SAMPLE);
    const seo = items.find((i) => i.text.includes('Local SEO'));
    expect(seo?.deadline).toBe('within 2 weeks');
  });

  it('drops page furniture, totals, GST lines, contact details and the signature block', () => {
    const { items } = parseQuoteDoc(SAMPLE);
    const texts = items.map((i) => i.text.toLowerCase());
    expect(texts.some((t) => t.startsWith('page'))).toBe(false);
    expect(texts.some((t) => t.includes('gst'))).toBe(false);
    expect(texts.some((t) => t.startsWith('total'))).toBe(false);
    expect(texts.some((t) => t.includes('@'))).toBe(false);
    expect(texts.some((t) => /^\+?\d[\d\s-]{7,}$/.test(t))).toBe(false);
    expect(texts.some((t) => t === 'signature')).toBe(false);
  });

  it('drops the long prose terms sentence but keeps short scope bullets', () => {
    const { items } = parseQuoteDoc(SAMPLE);
    expect(items.some((i) => i.text.includes('valid for thirty days'))).toBe(false);
    expect(items.length).toBeGreaterThanOrEqual(3);
  });

  it('handles bulleted/numbered lines by stripping the marker', () => {
    const { items } = parseQuoteDoc('- Discovery call\n1. Design mockup\n• Content collected');
    expect(items.map((i) => i.text)).toEqual(['Discovery call', 'Design mockup', 'Content collected']);
  });

  it('returns no items for an empty or whitespace-only document', () => {
    expect(parseQuoteDoc('').items).toEqual([]);
    expect(parseQuoteDoc('   \n\n  ').items).toEqual([]);
  });

  it('caps extraction at 60 items so a malformed extraction cannot flood the review screen', () => {
    const many = Array.from({ length: 200 }, (_, i) => `Line item number ${i}`).join('\n');
    expect(parseQuoteDoc(many).items.length).toBe(60);
  });
});

// Real text pulled with mammoth.extractRawText from a document generated by
// the agastyaone-quote skill's own generate_quote.js against its own real
// example input (examples/bangalore-dental.json) — not a guess. Verifies
// the anchor-based path actually matches the founder's real quote shape.
const REAL_AGASTYAONE_QUOTE = `
AGASTYAONE

Digital Growth Systems for Dental Clinics

Digital Growth Quotation

Website · Local SEO · Google Business Profile · Automation

Prepared For

Bangalore Dental & Cosmetology Institute, Banashankari

Contact Person

[Contact Name, Designation]

Quote Reference

AGO-Q-2026-001

Date

11 August 2026

Valid Until

26 August 2026

Prepared by

Agastya Kancharla

Founder, AgastyaOne

89515 53531 · agastya@agastyaone.com · agastyaone.com

11 August 2026

Dear [Contact Name],

Thank you for taking the time to meet with us. Following our discussion, this quotation sets out the scope, deliverables, and investment for the digital growth system we discussed for Bangalore Dental & Cosmetology Institute, Banashankari.

Each section below reflects exactly what was agreed — what you receive as part of the one-time setup, and what AgastyaOne continues to manage for you every month as part of the Monthly Growth Plan. Pricing is drawn directly from our published Commercial Catalogue, so there are no hidden charges.

We're happy to walk through any part of this quotation on a call before you confirm.

Local Visibility & Discovery

Google Business Profile

Setup Includes

Audit

Optimization

Verification support

Categories & services

Initial posts

Every Month

Weekly posts

Review responses

Photo updates

Insights report

Monitoring

What We're Fixing — Based on Your Audit

Here's exactly what our audit found, and what we'll correct as part of the setup above:

NAP & Business Identity

Correct business name spelling ("Cosmetolgy" → "Cosmetology") and align with Google's naming guidelines

Standardize your primary contact number across Google and existing directory listings (JustDial, etc.)

Beyond This Quote — Additional Opportunities

Your Google Business Profile is the foundation, but real local dominance comes from a consistent presence across the web.

Website

A dedicated website gives you a home base beyond Google Maps.

These are not part of the scope or pricing below — happy to share pricing and build a combined plan whenever you're ready.

Investment Summary

ONE-TIME INVESTMENT

₹3,000

Setup & optimization

MONTHLY GROWTH PLAN

OPTIONAL — IF REQUIRED

₹2,000/mo

Ongoing management

Service

One-Time Investment

Monthly Growth Plan (Optional)

Google Business Profile

₹3,000

₹2,000/mo

TOTAL (selected services only)

₹3,000

₹2,000/mo

* Optional monthly plans are billed only if you choose to continue them after setup.

What Happens Next

1.  Acceptance & Advance Payment — you confirm this quotation and share the agreed advance.

Payment Terms

One-Time Investment: 50% advance to begin work, 50% on delivery/launch.

Terms & Validity

This quotation is valid for 15 days from the date above.

Acceptance

By signing below, both parties confirm agreement to the scope and pricing outlined in this quotation.

For the Clinic

For AgastyaOne

Name: _______________________

Name: _______________________

AGASTYAONE

agastyaone.com  ·  agastya@agastyaone.com  ·  89515 53531
`;

describe('parseQuoteDoc — real AgastyaOne quote template', () => {
  it('extracts exactly the real Setup Includes / Every Month bullets, in order', () => {
    const { items } = parseQuoteDoc(REAL_AGASTYAONE_QUOTE);
    expect(items.map((i) => i.text)).toEqual([
      'Audit',
      'Optimization',
      'Verification support',
      'Categories & services',
      'Initial posts',
      'Weekly posts',
      'Review responses',
      'Photo updates',
      'Insights report',
      'Monitoring'
    ]);
  });

  it('categorizes every item under the service name and prices it from Investment Summary', () => {
    const { items } = parseQuoteDoc(REAL_AGASTYAONE_QUOTE);
    for (const item of items) {
      expect(item.category).toBe('Google Business Profile');
      expect(item.price).toBe('₹3,000');
      expect(item.deadline).toBeUndefined();
    }
  });

  it('excludes every non-scope section — letterhead, title, info table, audit findings, upsell, investment table, next steps, terms, acceptance', () => {
    const { items } = parseQuoteDoc(REAL_AGASTYAONE_QUOTE);
    const texts = items.map((i) => i.text);
    const noise = [
      'AGASTYAONE',
      'Digital Growth Systems for Dental Clinics',
      'Digital Growth Quotation',
      'Prepared For',
      'Bangalore Dental & Cosmetology Institute, Banashankari',
      'Google Business Profile', // the category itself, never an item's own text
      "NAP & Business Identity",
      'Website',
      'TOTAL (selected services only)',
      'What Happens Next',
      'Payment Terms',
      'Acceptance',
      'Name: _______________________'
    ];
    for (const line of noise) expect(texts).not.toContain(line);
    expect(items.length).toBe(10);
  });
});

// Synthetic but structurally identical to the real multi-service case
// (two "Service / One-Time Investment / Monthly Growth Plan" table rows
// plus a TOTAL row) — the real example only has one service, so this
// covers price-per-category disambiguation between two services.
const MULTI_SERVICE_QUOTE = `
AGASTYAONE

Digital Growth Quotation

Prepared For

Test Clinic

Local Visibility & Discovery

Google Business Profile

Setup Includes

Audit

Optimization

Every Month

Weekly posts

Review responses

Website Development

Setup Includes

Design mockup

Pages built

Every Month

Hosting

Maintenance

Investment Summary

Service

One-Time Investment

Monthly Growth Plan

Google Business Profile

₹3,000

₹2,000/mo

Website Development

₹80,000

TOTAL (selected services only)

₹83,000

₹2,000/mo

What Happens Next

1.  Acceptance & Advance Payment — you confirm this quotation.

Acceptance

By signing below, both parties confirm agreement.
`;

describe('parseQuoteDoc — multiple services', () => {
  it('gives each service its own correct price, not the other service\'s or the total', () => {
    const { items } = parseQuoteDoc(MULTI_SERVICE_QUOTE);
    const gbp = items.filter((i) => i.category === 'Google Business Profile');
    const web = items.filter((i) => i.category === 'Website Development');
    expect(gbp.map((i) => i.text)).toEqual(['Audit', 'Optimization', 'Weekly posts', 'Review responses']);
    expect(gbp.every((i) => i.price === '₹3,000')).toBe(true);
    expect(web.map((i) => i.text)).toEqual(['Design mockup', 'Pages built', 'Hosting', 'Maintenance']);
    expect(web.every((i) => i.price === '₹80,000')).toBe(true);
  });
});

// Real text pulled with mammoth.extractRawText from a second real founder
// upload (ToothCraftDental) — a 5-service, one-time-only quote (no monthly
// retainer). It surfaced a real gap the first fixture above couldn't catch:
// this document labels its second scope column "Included Free — Months 1
// to 4" instead of "Every Month".
const REAL_TOOTHCRAFT_QUOTE = `
AGASTYAONE

Digital Growth Systems for Dental Clinics

Digital Growth Quotation

Website · Google Business Profile · Local SEO · AI Search (GEO)

Prepared For

Tooth Craft Multi-speciality Dental Clinic, Seegehalli

Contact Person

Dr. Anwesha Paul, Founder & Chief Dental Surgeon

Quote Reference

AGO-Q-2026-002

Date

18 August 2026

Valid Until

2 September 2026

Prepared by

Agastya Kancharla

Founder, AgastyaOne

89515 53531 · agastya@agastyaone.com · agastyaone.com

18 August 2026

Dear Dr. Anwesha Paul,

Thank you for meeting with us and for the confidence you've placed in AgastyaOne. Following our discussion, this quotation sets out the complete scope, deliverables, timeline, and investment for the digital growth system we agreed on for Tooth Craft Multi-speciality Dental Clinic, Seegehalli.

Each section below reflects exactly what was agreed — what you receive as part of the one-time setup, and what AgastyaOne continues to manage for you during the complimentary support period that follows. This is a single one-time investment with no monthly retainer and no hidden charges.

We're happy to walk through any part of this quotation on a call before you confirm.

Website & Patient Booking System

Premium Clinic Website with Online Booking

Setup Includes

Custom mobile-first website — Home, Services, About Doctor, Contact

Individual treatment pages (RCT, implants, orthodontics, pediatric, whitening, extractions)

Online appointment booking with treatment selection, date & time slots

Click-to-call and WhatsApp button on every page

Patient testimonials section + live Google review widget

Dentist / LocalBusiness schema markup for Google and AI search engines

FAQ content structured for AI answer engines (GEO)

Hosting, domain and SSL — FREE for the first 12 months

Fast loading, SSL secured, works on all devices

Included Free — Months 1 to 4

Content updates — new services, offers, team changes

Page and copy refinements based on ranking performance

Security monitoring and uptime checks

Hosting, domain and SSL fully covered

Google Sheets Bookings Dashboard

Setup Includes

Every website booking flows automatically into a live Google Sheet

Captures patient name, phone, treatment, preferred date & time

Accessible from any phone or computer at the front desk

No new software for your team to learn

Setup and walkthrough for reception staff

Included Free — Months 1 to 4

Dashboard monitoring and troubleshooting

Adjustments to captured fields on request

Patient Communication & Reviews

WhatsApp Message Templates & Click-to-Send System

Setup Includes

Pre-written WhatsApp message templates for every patient touchpoint

Booking confirmation message — ready to send the moment an appointment is made

Appointment reminder message for the day before the visit

Post-treatment follow-up and thank-you message

Standard reply template for enquiries received outside clinic hours

One-click send: your reception or Dr. Paul taps the patient's entry, WhatsApp opens with the message pre-filled and ready to send

No typing required — staff simply review and press send

Setup and hands-on walkthrough for reception staff

Included Free — Months 1 to 4

Message template updates and wording refinements

New templates added for additional treatments or offers on request

Ongoing support for reception staff using the system

Google Review Generation System

Setup Includes

Pre-filled review request message with a one-tap direct link to your Google review page

Sent by your team after each appointment with a single click — no typing needed

Sent to every patient equally — fully compliant with Google's review policies

Internal feedback channel so any concerns reach you directly and early

Simple daily routine set up for reception so no patient is missed

Grows your review count steadily with minimal effort from your team

Included Free — Months 1 to 4

Replying to every new and existing Google review

Review velocity tracking and reporting

Message wording optimisation to improve response rates

Local Visibility, Directories & AI Search

Google Business Profile, Local SEO, Directory Listings, NAP & GEO

Setup Includes

Complete Google Business Profile audit and optimisation

Correct primary category plus all applicable secondary categories

Full services menu built out with descriptions for every treatment

Rewritten business description with Seegehalli / Kannamangala / Whitefield signals

Website link added to your profile — currently missing

Photo upload, hours, attributes and social profile links configured

Google Business Profile Q&A section fully populated with real patient questions and answers

New listings created across priority directories (Practo, Justdial, Sulekha, IDA and more)

NAP cleanup — name, address and phone standardised everywhere

Entity disambiguation from unrelated 'Tooth Craft' clinics in other cities

GEO — structured data and answer-formatted content so ChatGPT, Gemini, Claude and Perplexity can identify and recommend your clinic

Baseline AI search testing across major assistants, with follow-up adjustments

Included Free — Months 1 to 4

Google Business Profile posts published regularly

Photo and offer updates on your profile

Q&A section expanded as new patient questions emerge

Local ranking monitoring with grid scans

AI assistant visibility re-tested and content adjusted

Monthly visibility report — rankings, calls, direction requests

What We're Fixing — Based on Your Audit

Here's exactly what our audit found, and what we'll correct as part of the setup above:

Where You Stand Today

Your clinic holds a 4.9 rating from 46 reviews — one of the strongest reputations in the Seegehalli area

Profile Completeness — Immediate Fixes

No website link is connected to your Google Business Profile — this affects both your ranking and your ability to convert searchers into booked patients

Delivery Timeline & Included Support

Here is exactly what happens, and over what period, for Tooth Craft Multi-speciality Dental Clinic, Seegehalli:

Weeks 1 to 3 — Build & Setup

Kickoff: collection of clinic photos, treatment list, doctor credentials and branding inputs

Beyond This Quote — Additional Opportunities

Once the foundation above is live and generating results, there is a natural second phase we'd recommend for Tooth Craft Multi-speciality Dental Clinic, Seegehalli:

Advanced Patient Automation

Recall and reactivation campaigns for patients due for their next check-up, treatment-specific follow-up sequences, and automated post-treatment care instructions delivered over WhatsApp.

Investment Summary

Service

One-Time Investment

Recurring Monthly Fee

Premium Clinic Website with Online Booking

₹18,000

—

Google Sheets Bookings Dashboard

₹3,500

—

WhatsApp Message Templates & Click-to-Send System

₹6,000

—

Google Review Generation System

₹3,500

—

Google Business Profile, Local SEO, Directory Listings, NAP & GEO

₹9,000

—

TOTAL — ONE-TIME INVESTMENT

₹40,000

—

What Happens Next

1.  Acceptance & Advance Payment — you confirm this quotation and share the agreed advance.

Payment Terms

One-Time Investment: 50% advance to begin work (₹20,000), balance ₹20,000 on delivery/launch.

Terms & Validity

This quotation is valid for 15 days from the date above.

Acceptance

By signing below, both parties confirm agreement to the scope and pricing outlined in this quotation.

For the Clinic

For AgastyaOne

Name: _______________________

Name: _______________________

AGASTYAONE

agastyaone.com  ·  agastya@agastyaone.com  ·  89515 53531
`;

describe('parseQuoteDoc — real AgastyaOne quote template, second scope-column variant', () => {
  it('captures every "Setup Includes" and "Included Free — Months …" bullet under the right service', () => {
    const { items } = parseQuoteDoc(REAL_TOOTHCRAFT_QUOTE);

    const website = items.filter((i) => i.category === 'Premium Clinic Website with Online Booking');
    expect(website.map((i) => i.text)).toEqual([
      'Custom mobile-first website — Home, Services, About Doctor, Contact',
      'Individual treatment pages (RCT, implants, orthodontics, pediatric, whitening, extractions)',
      'Online appointment booking with treatment selection, date & time slots',
      'Click-to-call and WhatsApp button on every page',
      'Patient testimonials section + live Google review widget',
      'Dentist / LocalBusiness schema markup for Google and AI search engines',
      'FAQ content structured for AI answer engines (GEO)',
      'Hosting, domain and SSL — FREE for the first 12 months',
      'Fast loading, SSL secured, works on all devices',
      'Content updates — new services, offers, team changes',
      'Page and copy refinements based on ranking performance',
      'Security monitoring and uptime checks',
      'Hosting, domain and SSL fully covered'
    ]);
    expect(website.every((i) => i.price === '₹18,000')).toBe(true);

    const whatsapp = items.filter((i) => i.category === 'WhatsApp Message Templates & Click-to-Send System');
    expect(whatsapp.map((i) => i.text)).toEqual([
      'Pre-written WhatsApp message templates for every patient touchpoint',
      'Booking confirmation message — ready to send the moment an appointment is made',
      'Appointment reminder message for the day before the visit',
      'Post-treatment follow-up and thank-you message',
      'Standard reply template for enquiries received outside clinic hours',
      "One-click send: your reception or Dr. Paul taps the patient's entry, WhatsApp opens with the message pre-filled and ready to send",
      'No typing required — staff simply review and press send',
      'Setup and hands-on walkthrough for reception staff',
      'Message template updates and wording refinements',
      'New templates added for additional treatments or offers on request',
      'Ongoing support for reception staff using the system'
    ]);
    expect(whatsapp.every((i) => i.price === '₹6,000')).toBe(true);

    for (const item of items) expect(item.deadline).toBeUndefined();
  });

  it('never includes the marker headings themselves as an item', () => {
    const { items } = parseQuoteDoc(REAL_TOOTHCRAFT_QUOTE);
    const texts = items.map((i) => i.text.toLowerCase());
    expect(texts).not.toContain('setup includes');
    expect(texts.some((t) => t.startsWith('included free'))).toBe(false);
    expect(texts).not.toContain('every month');
  });

  it('prices every service correctly from the Investment Summary, not the total or another service\'s row', () => {
    const { items } = parseQuoteDoc(REAL_TOOTHCRAFT_QUOTE);
    const priceByCategory: Record<string, string> = {
      'Premium Clinic Website with Online Booking': '₹18,000',
      'Google Sheets Bookings Dashboard': '₹3,500',
      'WhatsApp Message Templates & Click-to-Send System': '₹6,000',
      'Google Review Generation System': '₹3,500',
      'Google Business Profile, Local SEO, Directory Listings, NAP & GEO': '₹9,000'
    };
    for (const [category, price] of Object.entries(priceByCategory)) {
      const group = items.filter((i) => i.category === category);
      expect(group.length).toBeGreaterThan(0);
      expect(group.every((i) => i.price === price)).toBe(true);
    }
    expect(items.some((i) => i.price === '₹40,000')).toBe(false);
  });

  it('excludes letterhead, audit findings, timeline, upsell, next steps, terms and acceptance', () => {
    const { items } = parseQuoteDoc(REAL_TOOTHCRAFT_QUOTE);
    const texts = items.map((i) => i.text);
    const noise = [
      'AGASTYAONE',
      'Prepared For',
      'Tooth Craft Multi-speciality Dental Clinic, Seegehalli',
      "What We're Fixing — Based on Your Audit",
      'Your clinic holds a 4.9 rating from 46 reviews — one of the strongest reputations in the Seegehalli area',
      'Delivery Timeline & Included Support',
      'Kickoff: collection of clinic photos, treatment list, doctor credentials and branding inputs',
      'Beyond This Quote — Additional Opportunities',
      'Advanced Patient Automation',
      'TOTAL — ONE-TIME INVESTMENT',
      'What Happens Next',
      'Payment Terms',
      'Acceptance',
      'Name: _______________________'
    ];
    for (const line of noise) expect(texts).not.toContain(line);
  });

  // Known, accepted limitation (documented in the parser's own comment):
  // generate_quote.js emits a broader section-heading line before a
  // service's own subheading only for the first service in a new top-level
  // section, and that can't be told apart from a real bullet by text shape
  // alone — so it occasionally lands as one extra item under the *previous*
  // service, at that service's price. Two such lines exist in this real
  // document. This is caught on the mandatory review screen before
  // anything reaches a client's checklist, same as any other imperfect
  // extraction — silently dropping a real bullet instead would be worse.
  it('may occasionally carry a stray section-heading line into the previous service (known, review-screen-caught limitation)', () => {
    const { items } = parseQuoteDoc(REAL_TOOTHCRAFT_QUOTE);
    const strays = items.filter((i) => i.text === 'Patient Communication & Reviews' || i.text === 'Local Visibility, Directories & AI Search');
    expect(strays.length).toBe(2);
  });
});
